# Generated by Django 4.2.20 on 2025-05-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the trip was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled the trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
