# Generated by Django 4.2.20 on 2025-05-10 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_trip_cancelled_at_trip_cancelled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', help_text='Status of the trip', max_length=10),
        ),
        migrations.CreateModel(
            name='TripNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trip_cancelled', 'Trip Cancelled'), ('new_member', 'New Member Joined'), ('trip_joined', 'Successfully Joined Trip'), ('trip_left', 'Member Left Trip'), ('trip_updated', 'Trip Details Updated'), ('review_reminder', 'Review Reminder')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth_app.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Notification',
                'verbose_name_plural': 'Trip Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
