# Generated by Django 4.2.20 on 2025-05-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_chatnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
