# Generated by Django 4.2.20 on 2025-05-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_chatnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotification',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth_app.chatmessage'),
        ),
        migrations.AlterField(
            model_name='tripnotification',
            name='notification_type',
            field=models.CharField(choices=[('trip_created', 'Trip Created'), ('trip_updated', 'Trip Updated'), ('trip_cancelled', 'Trip Cancelled'), ('buddy_request', 'Buddy Request'), ('buddy_accepted', 'Buddy Request Accepted'), ('buddy_declined', 'Buddy Request Declined'), ('trip_reminder', 'Trip Reminder'), ('new_member', 'New Member Joined')], max_length=20),
        ),
    ]
