# Generated by Django 4.2.20 on 2025-05-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_chatnotification_chat_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('silver', 'Silver Plan (Monthly)'), ('gold', 'Gold Plan (Annual)')], max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Notification',
                'verbose_name_plural': 'Trip Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='tripnotification',
            name='notification_type',
            field=models.CharField(choices=[('trip_cancelled', 'Trip Cancelled'), ('new_member', 'New Member Joined'), ('trip_joined', 'Successfully Joined Trip'), ('trip_left', 'Member Left Trip'), ('trip_updated', 'Trip Details Updated'), ('review_reminder', 'Review Reminder')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
