# Generated by Django 4.2.20 on 2025-05-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
