# Generated by Django 4.2.20 on 2025-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag to quickly identify cancelled trips'),
        ),
    ]
